import { gql } from '@apollo/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Carousel } from '../components/Carousel/Carousel';
import { mapResponseToCard } from '../components/Card/Card.utility';
import client from '../apollo-client';

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query MyQuery {
        program {
          thumnail {
            alt
            id
            url
          }
          name
          id
        }
      }
    `,
  });
  return {
    props: {
      programs: data.program,
    },
  };
}

const Home: NextPage = ({ programs }: any) => {
  const items = mapResponseToCard(programs);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container mx-auto w-full h-full flex items-center justify-center bg-gray-100'>
        <Carousel items={items} />
      </div>
    </>
  );
};

export default Home;
